import type { Metadata } from 'next'

// Single source of truth for absolute URLs and brand strings used in SEO metadata.
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? 'https://mojkmet.eu').replace(
  /\/$/,
  ''
)
export const SITE_NAME = 'mojkmet.eu'
export const SITE_TAGLINE = 'Sveže od kmeta, neposredno k vam'
export const SITE_DESCRIPTION =
  'Kupujte sveže kmetijske pridelke neposredno od slovenskih kmetov. Brez posrednikov, poštene cene, prevzem na kmetiji.'

const TITLE_TEMPLATE = `%s | ${SITE_NAME}`

// Share images are generated by app/opengraph-image.tsx and app/twitter-image.tsx. They are
// referenced explicitly (instead of relying on Next's file-based inheritance) because a page
// that sets its own `openGraph` would otherwise lose the image, and file-based URLs can
// resolve against the deployment host instead of metadataBase.
const SHARE_ALT = `${SITE_NAME} - ${SITE_TAGLINE}`
export const OG_IMAGES = [{ url: '/opengraph-image', width: 1200, height: 630, alt: SHARE_ALT }]
export const TWITTER_IMAGES = [{ url: '/twitter-image', width: 1200, height: 630, alt: SHARE_ALT }]

/**
 * Full per-page metadata. Next shallow-merges metadata, so a page that sets `openGraph`
 * replaces the layout's whole openGraph object; this keeps siteName/locale/images/twitter
 * intact. `title` is the bare page title (the root layout template appends the site name).
 *
 * Next resets the title template after every segment, so a layout that has child routes
 * with their own titles (e.g. /farms -> /farms/[id]) must pass `passTemplate` to keep the
 * "| mojkmet.eu" suffix flowing down to them.
 */
export function pageMetadata({
  title,
  description,
  path,
  noindex = false,
  passTemplate = false,
}: {
  title: string
  description?: string
  path: string
  noindex?: boolean
  passTemplate?: boolean
}): Metadata {
  const ogTitle = `${title} | ${SITE_NAME}`
  return {
    title: passTemplate ? { default: title, template: TITLE_TEMPLATE } : title,
    description,
    alternates: { canonical: path },
    ...(noindex ? { robots: { index: false, follow: false } } : {}),
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      locale: 'sl_SI',
      url: path,
      title: ogTitle,
      description,
      images: OG_IMAGES,
    },
    twitter: { card: 'summary_large_image', title: ogTitle, description, images: TWITTER_IMAGES },
  }
}

/** Trim to a search-snippet-friendly length without cutting mid-word. */
export function truncate(text: string | null | undefined, max = 160): string | undefined {
  if (!text) return undefined
  const clean = text.replace(/\s+/g, ' ').trim()
  if (clean.length <= max) return clean
  return clean.slice(0, max - 1).replace(/\s+\S*$/, '') + '…'
}
